Repository slackapi/deno-slack-hooks, pull requests merged in 2025-06, with the labels that each got.

#103 fix: check updates for known deps imported in deno configs & .slack/hooks
  src/check_update.ts
  src/install_update.ts
  src/tests/check_update_test.ts
  src/tests/install_update_test.ts
Labels: bug, semver:patch

#106 fix: support deno version 2.x
  .github/workflows/deno-cd.yml
  .github/workflows/deno-ci.yml
  deno.jsonc
  src/README.md
  src/build.ts
  src/check_update.ts
  src/dev_deps.ts
  src/doctor.ts
  src/get_manifest.ts
  src/get_trigger.ts
  src/install_update.ts
  src/tests/check_update_test.ts
  src/tests/doctor_test.ts
  src/tests/install_update_test.ts
  src/utilities.ts
Labels: enhancement, semver:patch, dependencies

#107 chore: release 1.4.0
  src/libraries.ts
  src/version.ts
Labels: semver:minor, dependencies
